/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VIEW;

import BUS.IQLSanPhamService;
import BUS.IQLThuocTinhSachService;
import BUS.QLSanPhamService;
import BUS.QLThuocTinhSachService;
import Models.TheLoai;
import Utilities.DiaLogMes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class CardTheLoai extends javax.swing.JDialog {
    DiaLogMes diaLogMes;
    DefaultTableModel model;
    IQLThuocTinhSachService _iQLThuocTinhSachService;
    IQLSanPhamService _iQLSanPhamService;
    List<TheLoai> _lstTheLoai;
    /**
     * Creates new form JDiaLogTheLoai
     */
    public CardTheLoai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        _iQLThuocTinhSachService = new QLThuocTinhSachService();
        _iQLSanPhamService = new QLSanPhamService();
        _lstTheLoai = new ArrayList<>();
        diaLogMes = new DiaLogMes();
        _lstTheLoai = _iQLThuocTinhSachService.getDataTL();
        filltableTL();
    }
    private void refreshTableTl() {
        _lstTheLoai = _iQLThuocTinhSachService.getDataTL();
        filltableTL();
    }

    private void findTenTL() {
        String tentl = txt_TenTL.getText();
        if (_iQLThuocTinhSachService.findTenTL(tentl).isEmpty()) {
            diaLogMes.alert(this, "Thông Tin Hiện Tại Không Khả Dụng");
        } else {
            _lstTheLoai = _iQLThuocTinhSachService.findTenTL(tentl);
            filltableTL();
        }
    }

    private void moiTL() {
        txt_MaTl.setText("");
        txt_TenTL.setText("");
        txt_Mota.setText("");
        refreshTableTl();
    }

    private void themTL() {
        TheLoai TL = getFormTL();
        if (_iQLThuocTinhSachService.insert_TL(TL)) {
            diaLogMes.alert(this, "Thêm Thành Công");
        } else {
            diaLogMes.alert(this, "Thêm Thất Bại");
        }
    }

    private void suaTL() {
        TheLoai TL = getFormTL();
        if (_iQLThuocTinhSachService.update_TL(TL)) {
            diaLogMes.alert(this, "Sửa Thành Công");
        } else {
            diaLogMes.alert(this, "Sửa Thất Bại");
        }
    }

    private void xoaTL() {
        String maTL = txt_MaTl.getText();
        if (_iQLThuocTinhSachService.delete_TL(maTL)) {
            diaLogMes.alert(this, "Xoá Thành Công");
        } else {
            diaLogMes.alert(this, "Xoá Thất Bại");
        }
    }

    private void clickTblTL() {
        int row = tblTheLoai.getSelectedRow();
        String mantl = (String) tblTheLoai.getValueAt(row, 0);
        String tentl = (String) tblTheLoai.getValueAt(row, 1);
        String mota = (String) tblTheLoai.getValueAt(row, 2);
        txt_MaTl.setText(mantl);
        txt_TenTL.setText(tentl);
        txt_Mota.setText(mota);

    }

    private TheLoai getFormTL() {
        TheLoai TL = new TheLoai();
        try {
            TL.setMa_TL(txt_MaTl.getText());
            TL.setTenTL(txt_TenTL.getText());
            TL.setMota(txt_Mota.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
        return TL;
    }

    private void filltableTL() {
        model = (DefaultTableModel) tblTheLoai.getModel();
        model.setRowCount(0);
        int stt = 1;
        if (_lstTheLoai.isEmpty()) {
            return;
        }
        for (TheLoai TL : _lstTheLoai) {
            if (TL.getTrangThai() != 2) {
                Object[] row = {
                    stt,
                    TL.getMa_TL(),
                    TL.getTenTL(),
                    TL.getMota(),
                    TL.getTrangThai()
                };
                model.addRow(row);
                stt++;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_TheLoai = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTheLoai = new javax.swing.JTable();
        pnl_ThongTinTL = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_TenTL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_Mota = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        btn_ThemTL = new javax.swing.JButton();
        btn_SuaTL = new javax.swing.JButton();
        btn_XoaTL = new javax.swing.JButton();
        btn_MoiTL = new javax.swing.JButton();
        btn_TimTL = new javax.swing.JButton();
        txt_MaTl = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnl_TheLoai.setBorder(javax.swing.BorderFactory.createTitledBorder("Thể Loại"));
        pnl_TheLoai.setOpaque(false);

        tblTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã TL", "Tên TL", "Mô Tả", "Trạng Thái"
            }
        ));
        tblTheLoai.setOpaque(false);
        tblTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTheLoaiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTheLoai);

        pnl_ThongTinTL.setOpaque(false);
        pnl_ThongTinTL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Tên Thể Loại");
        pnl_ThongTinTL.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        pnl_ThongTinTL.add(txt_TenTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        jLabel8.setText("Mô Tả");
        pnl_ThongTinTL.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txt_Mota.setColumns(20);
        txt_Mota.setRows(5);
        jScrollPane8.setViewportView(txt_Mota);

        pnl_ThongTinTL.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        btn_ThemTL.setText("Thêm");
        btn_ThemTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemTLActionPerformed(evt);
            }
        });
        jPanel14.add(btn_ThemTL);

        btn_SuaTL.setText("Sửa");
        btn_SuaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaTLActionPerformed(evt);
            }
        });
        jPanel14.add(btn_SuaTL);

        btn_XoaTL.setText("Xoá");
        btn_XoaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTLActionPerformed(evt);
            }
        });
        jPanel14.add(btn_XoaTL);

        btn_MoiTL.setText("Mới");
        btn_MoiTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoiTLActionPerformed(evt);
            }
        });
        jPanel14.add(btn_MoiTL);

        btn_TimTL.setText("Tìm");
        btn_TimTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimTLActionPerformed(evt);
            }
        });
        jPanel14.add(btn_TimTL);

        pnl_ThongTinTL.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 310, 30));

        txt_MaTl.setEnabled(false);
        pnl_ThongTinTL.add(txt_MaTl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, -1));

        jLabel13.setText("Mã TL");
        pnl_ThongTinTL.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        javax.swing.GroupLayout pnl_TheLoaiLayout = new javax.swing.GroupLayout(pnl_TheLoai);
        pnl_TheLoai.setLayout(pnl_TheLoaiLayout);
        pnl_TheLoaiLayout.setHorizontalGroup(
            pnl_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
            .addComponent(pnl_ThongTinTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_TheLoaiLayout.setVerticalGroup(
            pnl_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TheLoaiLayout.createSequentialGroup()
                .addComponent(pnl_ThongTinTL, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_TheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_TheLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTheLoaiMouseClicked
        // TODO add your handling code here:
        clickTblTL();
    }//GEN-LAST:event_tblTheLoaiMouseClicked

    private void btn_ThemTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemTLActionPerformed
        // TODO add your handling code here:
        themTL();
    }//GEN-LAST:event_btn_ThemTLActionPerformed

    private void btn_SuaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaTLActionPerformed
        // TODO add your handling code here:
        suaTL();
    }//GEN-LAST:event_btn_SuaTLActionPerformed

    private void btn_XoaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTLActionPerformed
        // TODO add your handling code here:
        xoaTL();
    }//GEN-LAST:event_btn_XoaTLActionPerformed

    private void btn_MoiTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoiTLActionPerformed
        // TODO add your handling code here:
        moiTL();
    }//GEN-LAST:event_btn_MoiTLActionPerformed

    private void btn_TimTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimTLActionPerformed
        // TODO add your handling code here:
        findTenTL();
    }//GEN-LAST:event_btn_TimTLActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MoiTL;
    private javax.swing.JButton btn_SuaTL;
    private javax.swing.JButton btn_ThemTL;
    private javax.swing.JButton btn_TimTL;
    private javax.swing.JButton btn_XoaTL;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnl_TheLoai;
    private javax.swing.JPanel pnl_ThongTinTL;
    private javax.swing.JTable tblTheLoai;
    private javax.swing.JTextField txt_MaTl;
    private javax.swing.JTextArea txt_Mota;
    private javax.swing.JTextField txt_TenTL;
    // End of variables declaration//GEN-END:variables
}
