/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VIEW;

import BUS.IQLSanPhamService;
import BUS.IQLThuocTinhSachService;
import BUS.QLSanPhamService;
import BUS.QLThuocTinhSachService;
import Models.KhuVucLuuTru;
import Utilities.DiaLogMes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class CardKhuVucLuuTru extends javax.swing.JDialog {
    DiaLogMes diaLogMes;
    DefaultTableModel model;
    IQLThuocTinhSachService _iQLThuocTinhSachService;
    IQLSanPhamService _iQLSanPhamService;
    List<KhuVucLuuTru> _lstKhuVucLuuTru;
    /** 
     * Creates new form JDiaLogKhuVucLuuTru
     */
    public CardKhuVucLuuTru(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        _iQLThuocTinhSachService = new QLThuocTinhSachService();
        _iQLSanPhamService = new QLSanPhamService();
        _lstKhuVucLuuTru = new ArrayList<>();
        diaLogMes = new DiaLogMes();
        _lstKhuVucLuuTru = _iQLThuocTinhSachService.getDataKV();
        filltableKV();
    }
    private void refreshTableKV() {
        _lstKhuVucLuuTru = _iQLThuocTinhSachService.getDataKV();
        filltableKV();
    }

    private void findTenKV() {
        String tenKV = txt_TenKV.getText();
        if (_iQLThuocTinhSachService.findTenKV(tenKV).isEmpty()) {
            diaLogMes.alert(this, "Thông Tin Hiện Tại Không Khả Dụng");
        } else {
            _lstKhuVucLuuTru = _iQLThuocTinhSachService.findTenKV(tenKV);
            filltableKV();
        }
    }

    private void moiKV() {
        txt_MaKV.setText("");
        txt_TenKV.setText("");
        refreshTableKV();
    }

    private void themKV() {
        KhuVucLuuTru kv = getFormKV();
        if (_iQLThuocTinhSachService.insert_KV(kv)) {
            diaLogMes.alert(this, "Thêm Thành Công");
        } else {
            diaLogMes.alert(this, "Thêm Thất Bại");
        }
    }

    private void suaKV() {
        KhuVucLuuTru kv = getFormKV();
        if (_iQLThuocTinhSachService.update_KV(kv)) {
            diaLogMes.alert(this, "Sửa Thành Công");
        } else {
            diaLogMes.alert(this, "Sửa Thất Bại");
        }
    }

    private void xoaKV() {
        String maKV = txt_MaKV.getText();
        if (_iQLThuocTinhSachService.delete_KV(maKV)) {
            diaLogMes.alert(this, "Xoá Thành Công");
        } else {
            diaLogMes.alert(this, "Xoá Thất Bại");
        }
    }

    private void clickTblKV() {
        int row = tblKhuVucLT.getSelectedRow();
        String mankv = (String) tblKhuVucLT.getValueAt(row, 0);
        String tenkv = (String) tblKhuVucLT.getValueAt(row, 1);
        txt_MaKV.setText(mankv);
        txt_TenKV.setText(tenkv);

    }

    private KhuVucLuuTru getFormKV() {
        KhuVucLuuTru kv = new KhuVucLuuTru();
        try {
            kv.setMa_KV(txt_MaKV.getText());
            kv.setTenKV(txt_TenKV.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
        return kv;
    }

    private void filltableKV() {
        model = (DefaultTableModel) tblKhuVucLT.getModel();
        model.setRowCount(0);
        int stt = 1;
        if (_lstKhuVucLuuTru.isEmpty()) {
            return;
        }
        for (KhuVucLuuTru kv : _lstKhuVucLuuTru) {
            if (kv.getTrangThai() != 2) {
                Object[] row = {
                    stt,
                    kv.getMa_KV(),
                    kv.getTenKV(),
                    kv.getTrangThai()
                };
                model.addRow(row);
                stt++;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_KVLuuTru = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblKhuVucLT = new javax.swing.JTable();
        pnl_ThongTinKVLT = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_TenKV = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        btn_ThemKV = new javax.swing.JButton();
        btn_SuaKV = new javax.swing.JButton();
        btn_XoaKV = new javax.swing.JButton();
        btn_MoiKV = new javax.swing.JButton();
        btn_TimKV = new javax.swing.JButton();
        txt_MaKV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnl_KVLuuTru.setBorder(javax.swing.BorderFactory.createTitledBorder("Khu Vực Lưu Trữ"));
        pnl_KVLuuTru.setOpaque(false);

        tblKhuVucLT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Stt", "MaKV", "TenKV", "Trạng Thái"
            }
        ));
        tblKhuVucLT.setOpaque(false);
        tblKhuVucLT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuVucLTMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblKhuVucLT);

        pnl_ThongTinKVLT.setOpaque(false);
        pnl_ThongTinKVLT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Tên Khu Vực");
        pnl_ThongTinKVLT.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        pnl_ThongTinKVLT.add(txt_TenKV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        btn_ThemKV.setText("Thêm");
        btn_ThemKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKVActionPerformed(evt);
            }
        });
        jPanel15.add(btn_ThemKV);

        btn_SuaKV.setText("Sửa");
        btn_SuaKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaKVActionPerformed(evt);
            }
        });
        jPanel15.add(btn_SuaKV);

        btn_XoaKV.setText("Xoá");
        btn_XoaKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaKVActionPerformed(evt);
            }
        });
        jPanel15.add(btn_XoaKV);

        btn_MoiKV.setText("Mới");
        btn_MoiKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoiKVActionPerformed(evt);
            }
        });
        jPanel15.add(btn_MoiKV);

        btn_TimKV.setText("Tìm");
        btn_TimKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKVActionPerformed(evt);
            }
        });
        jPanel15.add(btn_TimKV);

        pnl_ThongTinKVLT.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 310, 30));

        txt_MaKV.setEnabled(false);
        pnl_ThongTinKVLT.add(txt_MaKV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, -1));

        jLabel14.setText("Mã KV");
        pnl_ThongTinKVLT.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        javax.swing.GroupLayout pnl_KVLuuTruLayout = new javax.swing.GroupLayout(pnl_KVLuuTru);
        pnl_KVLuuTru.setLayout(pnl_KVLuuTruLayout);
        pnl_KVLuuTruLayout.setHorizontalGroup(
            pnl_KVLuuTruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
            .addComponent(pnl_ThongTinKVLT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_KVLuuTruLayout.setVerticalGroup(
            pnl_KVLuuTruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KVLuuTruLayout.createSequentialGroup()
                .addComponent(pnl_ThongTinKVLT, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_KVLuuTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_KVLuuTru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhuVucLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuVucLTMouseClicked
        // TODO add your handling code here:
        clickTblKV();
    }//GEN-LAST:event_tblKhuVucLTMouseClicked

    private void btn_ThemKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKVActionPerformed
        // TODO add your handling code here:
        themKV();
    }//GEN-LAST:event_btn_ThemKVActionPerformed

    private void btn_SuaKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaKVActionPerformed
        // TODO add your handling code here:
        suaKV();
    }//GEN-LAST:event_btn_SuaKVActionPerformed

    private void btn_XoaKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaKVActionPerformed
        // TODO add your handling code here:
        xoaKV();
    }//GEN-LAST:event_btn_XoaKVActionPerformed

    private void btn_MoiKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoiKVActionPerformed
        // TODO add your handling code here:
        moiKV();
    }//GEN-LAST:event_btn_MoiKVActionPerformed

    private void btn_TimKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKVActionPerformed
        // TODO add your handling code here:
        findTenKV();
    }//GEN-LAST:event_btn_TimKVActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MoiKV;
    private javax.swing.JButton btn_SuaKV;
    private javax.swing.JButton btn_ThemKV;
    private javax.swing.JButton btn_TimKV;
    private javax.swing.JButton btn_XoaKV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnl_KVLuuTru;
    private javax.swing.JPanel pnl_ThongTinKVLT;
    private javax.swing.JTable tblKhuVucLT;
    private javax.swing.JTextField txt_MaKV;
    private javax.swing.JTextField txt_TenKV;
    // End of variables declaration//GEN-END:variables
}
