/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;


import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author Hieu
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        updateDateTime(lbl_Time);
        setBoderPanelDefault();
    }
    private void openQuanLySach(){
        try {
            showFrom(new cardQuanLySach());
        } catch (Exception e) {
        }
    }
    private void showFrom(Component com) {
        pnl_body.removeAll();
        pnl_body.add(com);
        pnl_body.revalidate();
        pnl_body.repaint();
    }
    private void setEffectDefault() {
        Color color = Color.white;
//        Color color = new Color(204,204,204);
        pnl_TrangChu.setBackground(color);
        pnl_BanHang.setBackground(color);
        pnl_HoaDon.setBackground(color);
        pnl_QuanLySach.setBackground(color);
//        pnl_ThongKe.setBackground(color);
        pnl_NhanVien.setBackground(color);
        pnl_KhachHang.setBackground(color);
//        pnl_DangXuat.setBackground(color);

    }

    private void setEffectButton(JPanel pnl) {
        pnl.setBackground(new Color(255, 153, 153));
    }

    private void setEffectHover(JPanel pnl) {
        pnl.setBackground(new Color(255, 204, 204));
    }
    private void setBoderPanelDefault() {
//        Color color = Color.white;
        Color color = new Color(255, 214, 193);
        Border roundedBorder = BorderFactory.createLineBorder(color, 3, true);
        pnl_TrangChu.setBorder(roundedBorder);
        pnl_BanHang.setBorder(roundedBorder);
        pnl_QuanLySach.setBorder(roundedBorder);
        pnl_NhanVien.setBorder(roundedBorder);
        pnl_KhachHang.setBorder(roundedBorder);
        pnl_HoaDon.setBorder(roundedBorder);

//        pnl_ThongKe.setBorder(roundedBorder);

//        pnl_DangXuat.setBorder(roundedBorder);

    }
    private void updateDateTime(JLabel dateTimeLabel) {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Lấy ngày giờ hiện tại
                Date now = new Date();
                // Định dạng ngày giờ theo định dạng mong muốn
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                String dateTime = dateFormat.format(now);
                // Hiển thị ngày giờ trên JLabel
                dateTimeLabel.setText("Thời Gian: " + dateTime);
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Bg = new javax.swing.JPanel();
        pnl_ChucNang = new javax.swing.JPanel();
        pnl_logo = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        pnl_body = new javax.swing.JPanel();
        lbl_Time = new javax.swing.JLabel();
        pnl_TrangChu = new javax.swing.JPanel();
        lbl_TrangChu = new javax.swing.JLabel();
        pnl_BanHang = new javax.swing.JPanel();
        lbl_BanHang = new javax.swing.JLabel();
        pnl_QuanLySach = new javax.swing.JPanel();
        lbl_QuanLySach = new javax.swing.JLabel();
        pnl_NhanVien = new javax.swing.JPanel();
        lbl_NhanVien = new javax.swing.JLabel();
        pnl_KhachHang = new javax.swing.JPanel();
        lbl_KhachHang = new javax.swing.JLabel();
        pnl_HoaDon = new javax.swing.JPanel();
        lbl_HoaDon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 760));
        setResizable(false);

        pnl_Bg.setBackground(new java.awt.Color(255, 255, 255));

        pnl_ChucNang.setBackground(new java.awt.Color(204, 204, 204));
        pnl_ChucNang.setOpaque(false);
        pnl_ChucNang.setPreferredSize(new java.awt.Dimension(1280, 720));

        pnl_logo.setBackground(new java.awt.Color(255, 255, 255));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_main.png"))); // NOI18N
        lbl_logo.setText("LoGo");

        javax.swing.GroupLayout pnl_logoLayout = new javax.swing.GroupLayout(pnl_logo);
        pnl_logo.setLayout(pnl_logoLayout);
        pnl_logoLayout.setHorizontalGroup(
            pnl_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_logoLayout.createSequentialGroup()
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_logoLayout.setVerticalGroup(
            pnl_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_logoLayout.createSequentialGroup()
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_body.setBackground(new java.awt.Color(255, 239, 213));
        pnl_body.setPreferredSize(new java.awt.Dimension(1700, 1080));
        pnl_body.setLayout(new java.awt.GridLayout(1, 0));

        lbl_Time.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Time.setText("Thời Gian");

        pnl_TrangChu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_TrangChu.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_TrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TrangChuMouseEntered(evt);
            }
        });

        lbl_TrangChu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_TrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeMain.png"))); // NOI18N
        lbl_TrangChu.setText("Trang Chủ");

        javax.swing.GroupLayout pnl_TrangChuLayout = new javax.swing.GroupLayout(pnl_TrangChu);
        pnl_TrangChu.setLayout(pnl_TrangChuLayout);
        pnl_TrangChuLayout.setHorizontalGroup(
            pnl_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_TrangChuLayout.setVerticalGroup(
            pnl_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnl_BanHang.setBackground(new java.awt.Color(255, 255, 255));
        pnl_BanHang.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_BanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TrangChuMouseEntered(evt);
            }
        });

        lbl_BanHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeMain.png"))); // NOI18N
        lbl_BanHang.setText("Bán Hàng");

        javax.swing.GroupLayout pnl_BanHangLayout = new javax.swing.GroupLayout(pnl_BanHang);
        pnl_BanHang.setLayout(pnl_BanHangLayout);
        pnl_BanHangLayout.setHorizontalGroup(
            pnl_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_BanHangLayout.setVerticalGroup(
            pnl_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnl_QuanLySach.setBackground(new java.awt.Color(255, 255, 255));
        pnl_QuanLySach.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_QuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_QuanLySachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TrangChuMouseEntered(evt);
            }
        });

        lbl_QuanLySach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_QuanLySach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeMain.png"))); // NOI18N
        lbl_QuanLySach.setText("Quản Lý Sách");

        javax.swing.GroupLayout pnl_QuanLySachLayout = new javax.swing.GroupLayout(pnl_QuanLySach);
        pnl_QuanLySach.setLayout(pnl_QuanLySachLayout);
        pnl_QuanLySachLayout.setHorizontalGroup(
            pnl_QuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_QuanLySach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_QuanLySachLayout.setVerticalGroup(
            pnl_QuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_QuanLySach, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnl_NhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnl_NhanVien.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TrangChuMouseEntered(evt);
            }
        });

        lbl_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeMain.png"))); // NOI18N
        lbl_NhanVien.setText("Nhân Viên");

        javax.swing.GroupLayout pnl_NhanVienLayout = new javax.swing.GroupLayout(pnl_NhanVien);
        pnl_NhanVien.setLayout(pnl_NhanVienLayout);
        pnl_NhanVienLayout.setHorizontalGroup(
            pnl_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_NhanVienLayout.setVerticalGroup(
            pnl_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnl_KhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnl_KhachHang.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_KhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TrangChuMouseEntered(evt);
            }
        });

        lbl_KhachHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeMain.png"))); // NOI18N
        lbl_KhachHang.setText("Khách Hàng");

        javax.swing.GroupLayout pnl_KhachHangLayout = new javax.swing.GroupLayout(pnl_KhachHang);
        pnl_KhachHang.setLayout(pnl_KhachHangLayout);
        pnl_KhachHangLayout.setHorizontalGroup(
            pnl_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_KhachHangLayout.setVerticalGroup(
            pnl_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnl_HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnl_HoaDon.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_HoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TrangChuMouseEntered(evt);
            }
        });

        lbl_HoaDon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeMain.png"))); // NOI18N
        lbl_HoaDon.setText("Hoá Đơn");

        javax.swing.GroupLayout pnl_HoaDonLayout = new javax.swing.GroupLayout(pnl_HoaDon);
        pnl_HoaDon.setLayout(pnl_HoaDonLayout);
        pnl_HoaDonLayout.setHorizontalGroup(
            pnl_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_HoaDonLayout.setVerticalGroup(
            pnl_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_ChucNangLayout = new javax.swing.GroupLayout(pnl_ChucNang);
        pnl_ChucNang.setLayout(pnl_ChucNangLayout);
        pnl_ChucNangLayout.setHorizontalGroup(
            pnl_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ChucNangLayout.createSequentialGroup()
                .addGroup(pnl_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_ChucNangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ChucNangLayout.createSequentialGroup()
                        .addGroup(pnl_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pnl_BanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pnl_QuanLySach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pnl_NhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pnl_KhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pnl_HoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_body, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
        pnl_ChucNangLayout.setVerticalGroup(
            pnl_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ChucNangLayout.createSequentialGroup()
                .addGroup(pnl_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ChucNangLayout.createSequentialGroup()
                        .addComponent(pnl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_QuanLySach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_body, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Time)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_BgLayout = new javax.swing.GroupLayout(pnl_Bg);
        pnl_Bg.setLayout(pnl_BgLayout);
        pnl_BgLayout.setHorizontalGroup(
            pnl_BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_BgLayout.setVerticalGroup(
            pnl_BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BgLayout.createSequentialGroup()
                .addComponent(pnl_ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_TrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TrangChuMouseEntered
        // TODO add your handling code here:
        setEffectDefault();
        JPanel pnl = (JPanel) evt.getSource();
        setEffectHover(pnl);
    }//GEN-LAST:event_pnl_TrangChuMouseEntered

    private void pnl_TrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TrangChuMouseClicked
        // TODO add your handling code here:
        JPanel pnl = (JPanel) evt.getSource();
        setEffectButton(pnl);
    }//GEN-LAST:event_pnl_TrangChuMouseClicked

    private void pnl_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BanHangMouseClicked
        // TODO add your handling code here:
        JPanel pnl = (JPanel) evt.getSource();
        setEffectButton(pnl);
    }//GEN-LAST:event_pnl_BanHangMouseClicked

    private void pnl_QuanLySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_QuanLySachMouseClicked
        // TODO add your handling code here:
        JPanel pnl = (JPanel) evt.getSource();
        setEffectButton(pnl);
        openQuanLySach();
    }//GEN-LAST:event_pnl_QuanLySachMouseClicked

    private void pnl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_NhanVienMouseClicked
        // TODO add your handling code here:
        JPanel pnl = (JPanel) evt.getSource();
        setEffectButton(pnl);
    }//GEN-LAST:event_pnl_NhanVienMouseClicked

    private void pnl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_KhachHangMouseClicked
        // TODO add your handling code here:
        JPanel pnl = (JPanel) evt.getSource();
        setEffectButton(pnl);
    }//GEN-LAST:event_pnl_KhachHangMouseClicked

    private void pnl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_HoaDonMouseClicked
        // TODO add your handling code here:
        JPanel pnl = (JPanel) evt.getSource();
        setEffectButton(pnl);
    }//GEN-LAST:event_pnl_HoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_BanHang;
    private javax.swing.JLabel lbl_HoaDon;
    private javax.swing.JLabel lbl_KhachHang;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_QuanLySach;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_TrangChu;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JPanel pnl_BanHang;
    private javax.swing.JPanel pnl_Bg;
    private javax.swing.JPanel pnl_ChucNang;
    private javax.swing.JPanel pnl_HoaDon;
    private javax.swing.JPanel pnl_KhachHang;
    private javax.swing.JPanel pnl_NhanVien;
    private javax.swing.JPanel pnl_QuanLySach;
    private javax.swing.JPanel pnl_TrangChu;
    private javax.swing.JPanel pnl_body;
    private javax.swing.JPanel pnl_logo;
    // End of variables declaration//GEN-END:variables
}
